name: Build and Release
on:
  push:
    tags:
      - "v*"
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc make zip

      - name: Build PK3
        run: make distclean && make

      #- name: Upload PK3
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: release
      #    path: build/z-ratmod-*.pk3
      - name: Create a Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/z-ratmod-*.pk3
